# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='myfiles')),
                ('status', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
